In [1]:
import pandas as pd
import numpy as np

In [25]:
df= pd.read_csv(r'D:\krish naik - udemy ML and Deep Learning\CampusX\Feature Engineering\customer.csv')
df.sample(5)

age  gender   review education purchased
48   39  Female     Good        UG       Yes
3    72  Female     Good        PG        No
23   96  Female     Good    School        No
6    18    Male     Good    School        No
34   86    Male  Average    School        No

In [27]:
# Apply Ordinal Encoding on Review and Education column
# Apply Label Encoder on purchased column

df = df.iloc[:,2:]
df.sample(5)

review education purchased
8   Average        UG        No
39     Poor        PG        No
2      Good        PG        No
35     Poor    School       Yes
15     Poor        UG        No

In [29]:
# Whenever we do any kind of feature Transformation,First thing is to do is train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [31]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(40, 2) (10, 2) (40,) (10,)


In [33]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [35]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [39]:
from sklearn.preprocessing import OrdinalEncoder
ord_enc = OrdinalEncoder(categories=[['Poor','Average','Good'],['School', 'UG', 'PG']])
# We make List and create list within it depends on as to how many categorical column we want to transform
# categories parameter is optional, but it is desirable to select categries (based on scale of lowest to highest) otherwise
# OrdinalEncoder class will generate ratings randomly
# Lowest to Highest

In [41]:
ord_enc.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [43]:
X_train = ord_enc.transform(X_train)

In [45]:
X_train

array([[1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [2., 2.],
       [0., 2.]])

In [47]:
ord_enc.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [49]:
from sklearn.preprocessing import LabelEncoder
lab_enc = LabelEncoder()

In [51]:
lab_enc.fit(y_train)

LabelEncoder()

In [53]:
lab_enc.classes_  #[No --> 0 and Yes -->1]

array(['No', 'Yes'], dtype=object)

In [55]:
y_train = lab_enc.transform(y_train)
y_test = lab_enc.transform(y_test)

In [57]:
y_train

array([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0])

In [59]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

#### One Hot Encoding(OHE)

In [62]:
import pandas as pd
import numpy as np

In [132]:
cars = pd.read_csv(r'D:\krish naik - udemy ML and Deep Learning\CampusX\Feature Engineering\cars.csv')
cars.sample(5)

brand  km_driven    fuel                 owner  selling_price
3291  Maruti      90000  Diesel  Fourth & Above Owner         250000
4675    Tata      16000  Diesel           First Owner        1650000
647    Lexus      20000  Petrol           First Owner        5150000
7887    Tata      80000  Diesel           First Owner         434999
3864   Honda     140000  Diesel           Third Owner         350000

In [70]:
cars['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [72]:
cars['brand'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [74]:
cars['brand'].nunique()

32

In [78]:
cars['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [80]:
cars['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

#### One Hot Encoding using Pandas

In [190]:
pd.get_dummies(cars,columns = ['fuel','owner'],dtype=np.int32)

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

In [93]:
# Use .astype(int) on the resulting DataFrame to convert any Boolean values to integers explicitly
# cars_dummies = pd.get_dummies(cars, columns=['fuel', 'owner']).astype(int)

cars_dummies = pd.get_dummies(cars, columns=['fuel', 'owner'])
cars_dummies = cars_dummies.applymap(int)

C:\Users\porep\AppData\Local\Temp\ipykernel_11024\1747661426.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  cars_dummies = cars_dummies.applymap(int)


ValueError: invalid literal for int() with base 10: 'Maruti'

#### N-1 columns Using OneHotEncoding pandas

In [188]:
pd.get_dummies(cars,columns = ['fuel','owner'],drop_first=True,dtype = np.int32)
# One column is eliminated from both the categories


# Pandas doesn't remember which column has been placed at which position after dummies operation so it is not recommendable to
# use get.dummies to create dummy columns in M.L

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

In [99]:
cars.sample(5)

brand  km_driven    fuel         owner  selling_price
4902   Maruti      20000  Diesel   First Owner         600000
6422     Tata      50000  Petrol   First Owner         459999
3477     Ford      50000  Petrol  Second Owner         388000
1981  Hyundai       7000  Petrol   First Owner         540000
4329   Toyota      79328  Diesel  Second Owner         750000

#### OneHotEncoding using Sklearn

In [134]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(cars.iloc[:,0:4],cars.iloc[:,-1],test_size=0.2,random_state=2)

In [160]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=np.int32) # Drops first column of each categorical column to avoid Multi-collinearity
ohe.fit_transform(X_train[['fuel','owner']])
# One Hot Encoder creates sparse matrix

<6502x7 sparse matrix of type '<class 'numpy.int32'>'
	with 8746 stored elements in Compressed Sparse Row format>

In [140]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [142]:
X_train_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [144]:
X_train[['brand','km_driven']].values  # Values operation converts into numpy array

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], dtype=object)

In [146]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [158]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output= False,dtype=np.int32) # Drops first column of each categorical column to avoid Multi-collinearity
X_train_nosparse =  ohe.fit_transform(X_train[['fuel','owner']])
X_test_nosparse = ohe.transform(X_test[['fuel','owner']])

In [154]:
X_train_nosparse.shape

(6502, 7)

In [156]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

#### OneHotEncoding with Top Categories

In [163]:
counts = cars['brand'].value_counts()

In [165]:
cars['brand'].nunique()

32

In [182]:
# Categories under brand column , if the count is below 100 then clubbing into one single category "Others"
threshold  = 100
repl = counts[counts <= threshold].index  # behave like key and values of dictionary


In [186]:
pd.get_dummies(cars['brand'].replace(repl,'Uncommon'),dtype = np.int32)

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
0       0          0     0      0        0         0       1        0      0   
1       0          0     0      0        0         0       0        0      1   
2       0          0     0      1        0         0       0        0      0   
3       0          0     0      0        1         0       0        0      0   
4       0          0     0      0        0         0       1        0      0   
...   ...        ...   ...    ...      ...       ...     ...      ...    ...   
8123    0          0     0      0        1         0       0        0      0   
8124    0          0     0      0        1         0       0        0      0   
8125    0          0     0      0        0         0       1        0      0   
8126    0          0     0      0        0         0       0        0      0   
8127    0          0     0      0        0         0       0        0      0   

      Tata  Toyota  Uncommon  Volkswagen  
0        0       0         0           0  
1        0       0         0           0  
2        0       0         0           0  
3        0       0         0           0  
4        0       0         0           0  
...    ...     ...       ...         ...  
8123     0       0         0           0  
8124     0       0         0           0  
8125     0       0         0           0  
8126     1       0         0           0  
8127     1       0         0           0  

[8128 rows x 13 columns]

#### Column Transformers Application

In [193]:
import pandas as pd
import numpy as np

In [197]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [199]:
covid_dummy  = pd.read_csv(r'D:\krish naik - udemy ML and Deep Learning\CampusX\Feature Engineering\covid_toy.csv')

In [201]:
covid_dummy.sample(5)

age  gender  fever   cough       city has_covid
90   59  Female   99.0  Strong      Delhi        No
35   82  Female  102.0  Strong  Bangalore        No
16   69  Female  103.0    Mild    Kolkata       Yes
82   24    Male   98.0    Mild    Kolkata       Yes
38   49  Female  101.0    Mild      Delhi       Yes

In [205]:
covid_dummy['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [207]:
covid_dummy['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [211]:
covid_dummy.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [215]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(covid_dummy.drop(columns = ['has_covid']),covid_dummy['has_covid'],
                                                                  test_size = 0.2)

In [217]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(80, 5) (20, 5) (80,) (20,)


#### Traditional Method

In [220]:
si = SimpleImputer()

In [222]:
# adding simple imputer to fever col
X_train_fever = si.fit_transform(X_train[['fever']])
# also on test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [236]:
# Ordinalencoding --> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# Also on test Data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape,X_test_cough.shape

((80, 1), (20, 1))

In [234]:
# OneHotEncoding ---> gender,city
ohe = OneHotEncoder(drop = 'first',sparse_output = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape,X_test_gender_city.shape

((80, 4), (20, 4))

In [244]:
# Extracting Age
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values

# Also the test data
X_test_age = X_test.drop(columns = ['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [250]:
# Concatenate the train dataset
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis =1 )
# Also the test Data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis =1)

X_train_transformed.shape

(80, 7)

#### Optimised Approach

In [253]:
from sklearn.compose import ColumnTransformer

In [273]:
transformer = ColumnTransformer(transformers= [
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output = False ,drop='first'),['gender','city'])
],remainder ='passthrough')
# transformers ---> The columns on which transformers have to be applied {Transformation is required}
# remainder -----> The columns on which not any kind of transformation is required {'drop','passthrough'}
# passthrough ---> Not to apply anything on the columns
# drop --> to drop the column from the object created 

In [275]:
transformer.fit_transform(X_train)

array([[ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  70.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  24.        ],
       [100.85135135,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.    

In [277]:
transformer.fit_transform(X_train).shape

(80, 7)

In [279]:
transformer.transform(X_test)

array([[100.85135135,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [100.85135135,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [281]:
transformer.transform(X_test).shape

(20, 7)